### ISSUE TITLE
H5DOappendTestSWMR1 fails

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#64]
Not sure what's going on. Sometimes it seems to be locking the file. Other times it appears that the call itself is failing. Weird.

**Comment by gheber** [comment]
Test Name:	H5DOappendTestSWMR1
Test FullName:	UnitTests.H5SWMRTest.H5DOappendTestSWMR1
Test Source:	c:\Users\gerd\GitHub\HDF.PInvoke\UnitTests\H5SWMRTest\H5DOappend.cs : line 34
Test Outcome:	Failed
Test Duration:	0:00:00.0221733

Result Message:	
Assert.IsTrue failed. 
TestCleanup method UnitTests.H5SWMRTest.Cleanup threw exception. System.IO.IOException: System.IO.IOException: The process cannot access the file 'C:\Users\gerd\AppData\Local\Temp\tmpE734.tmp' because it is being used by another process..
Result StackTrace:	
at UnitTests.H5SWMRTest.H5DOappendTestSWMR1() in c:\Users\gerd\GitHub\HDF.PInvoke\UnitTests\H5SWMRTest\H5DOappend.cs:line 58

TestCleanup Stack Trace
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at UnitTests.H5SWMRTest.Cleanup() in c:\Users\gerd\GitHub\HDF.PInvoke\UnitTests\H5SWMRTest\H5SWMRTest.cs:line 107

**Comment by gheber** [comment]
There appears to be a bug(?) in H5DOappend. The function fails, if no append callback was registered, I filed a JIRA ticket ([HDFFV-9960](https://jira.hdfgroup.org/browse/HDFFV-9960)).

**Comment by gheber** [comment]
Fixed in pull request #75
