### ISSUE TITLE
H5Odisable_mdc_flushesTestSWMR[3,4] fail

### ISSUE THREAD

**Issue by gheber** [HDFGroup/HDF.PInvoke#65]
Both fail with a file locking message such as this:

```
Test Name:	H5Odisable_mdc_flushesTestSWMR3
Test FullName:	UnitTests.H5SWMRTest.H5Odisable_mdc_flushesTestSWMR3
Test Source:	c:\Users\gerd\GitHub\HDF.PInvoke\UnitTests\H5SWMRTest\H5Odisable_mdc_flushes.cs : line 56
Test Outcome:	Failed
Test Duration:	0:00:00.0223386

Result Message:	
Assert.IsTrue failed. 
TestCleanup method UnitTests.H5SWMRTest.Cleanup threw exception. System.IO.IOException: System.IO.IOException: The process cannot access the file 'C:\Users\gerd\AppData\Local\Temp\tmp3A19.tmp' because it is being used by another process..
Result StackTrace:	
at UnitTests.H5SWMRTest.H5Odisable_mdc_flushesTestSWMR3() in c:\Users\gerd\GitHub\HDF.PInvoke\UnitTests\H5SWMRTest\H5Odisable_mdc_flushes.cs:line 62

TestCleanup Stack Trace
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at UnitTests.H5SWMRTest.Cleanup() in c:\Users\gerd\GitHub\HDF.PInvoke\UnitTests\H5SWMRTest\H5SWMRTest.cs:line 107
```

**Comment by gheber** [comment]
Try to bump the H5F close degree.

**Comment by gheber** [comment]
That appears to fix it.

**Comment by gheber** [comment]
Fixed in pull request #75
